### ISSUE TITLE
Self play?

### ISSUE THREAD

**Issue by pcholt** [aalekhpatel07/minimax#2]
I'm a little surprised that this self-play test doesn't work?

```rust
    #[test]
    fn test_should_always_tie_a_3_by_3_after_9_moves_at_depth_9() {
        let mut ttt = TicTacToe::create_game(3, None, None, None);
        for move_number in 0..=8 {
            let is_maximising = move_number%2 == 0;
            let i = ttt.get_best_move(9, is_maximising);
            ttt.play(&i, is_maximising);
            ttt.print_board();
        }
        assert!(ttt.is_game_complete());
        assert!(ttt.is_game_tied());
    }
```

**Comment by aalekhpatel07** [comment]
That looks like an interesting test case. My initial guess is `get_best_move` spits out an invalid move but I'm not too sure. 
I'll investigate it further soon. 

Thanks for creating the issue!

**Comment by aalekhpatel07** [comment]
Yep that was indeed an error in the implementation of Alpha-Beta pruning. Thank you for bringing it to light. #3 fixes it.
You may use the version `0.2.0` by installing with `cargo install minimax-alpha-beta --version 0.2.0`
